# SAIFEN — Supabase CLI config
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "saifen"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[studio]
enabled = true
port = 54323

[inbucket]                            # email testing
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:8000"
additional_redirect_urls = ["http://localhost:8000/web/"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
verify_jwt = true
